// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagementApp.Models.Database;

namespace ProjectManagementApp.Models.Database.Migrations
{
    [DbContext(typeof(ProjectManagementDbContext))]
    [Migration("20210401123300_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectManagementApp.Models.Database.Entities.BoardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("board");
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Database.Entities.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemListEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemListEntityId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Database.Entities.ItemListEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BoardEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardEntityId");

                    b.ToTable("itemlist");
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Database.Entities.ItemEntity", b =>
                {
                    b.HasOne("ProjectManagementApp.Models.Database.Entities.ItemListEntity", null)
                        .WithMany("ItemEntities")
                        .HasForeignKey("ItemListEntityId");
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Database.Entities.ItemListEntity", b =>
                {
                    b.HasOne("ProjectManagementApp.Models.Database.Entities.BoardEntity", null)
                        .WithMany("ItemListEntities")
                        .HasForeignKey("BoardEntityId");
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Database.Entities.BoardEntity", b =>
                {
                    b.Navigation("ItemListEntities");
                });

            modelBuilder.Entity("ProjectManagementApp.Models.Database.Entities.ItemListEntity", b =>
                {
                    b.Navigation("ItemEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
